### ISSUE TITLE
Feature request: Make all messages localizable

### ISSUE THREAD

**Issue by SlimeDog** [GorgeousOne/TangledMazes#10]
**Is your feature request related to a problem? Please describe.**
All messages should be localizable, to conform with server-wide design

**Describe the solution you'd like**
Create language file(s) to specify all messages.
Support /tm reload command (console or in-game) to reload configuration, so that changes can be tested without restarting the server.

**Environment**
Spigot 1.13.2
TangleMaze 1.2

**Comment by GorgeousOne** [comment]
implemented
