### ISSUE TITLE
Request for ceiling and floor commands added

### ISSUE THREAD

**Issue by GothkittyGirl** [GorgeousOne/TangledMazes#17]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is, e.g. "I'm always frustrated when ..."

**Add the option to add a floor and ceiling to the commands for those with dynmap that want to hide the paths.**

**I have w/ed in the floor and ceiling before i found this plugin but think it would be a great addtion to add these two to the list so that you can add it it you want to**

**Additional context**

**Comment by GorgeousOne** [comment]
Could you describe commands that you would like to be added in order to create a ceiling or a floor?

**Comment by GothkittyGirl** [comment]
well it would be like you do with the walls

**Comment by GorgeousOne** [comment]
So you suggest that after using the /build command there should be the option to run a /floor or /ceiling command where you could specify blocks types too?

**Comment by GothkittyGirl** [comment]
yes please

**Comment by GorgeousOne** [comment]
I am about to finish your request finally xD I only need take some more pictures for the website

**Comment by GothkittyGirl** [comment]
awesome! thx
