### ISSUE TITLE
wand breaks blocks

### ISSUE THREAD

**Issue by YaliOz** [GorgeousOne/TangledMazes#22]
When I do /maze wand I get the wand but when I left click a block it just breaks and says nothing in chat

**Comment by GorgeousOne** [comment]
Does TangledMaze load properly? Are there any errors showing up in the console when starting the server?

**Comment by YaliOz** [comment]
Yes and I reloaded the plugin several times.
Maybe it's because of WorldEdit?

**Comment by GorgeousOne** [comment]
I'm running WorldEdit and TangledMaze together without any problems.
Can you tell me what other plugins you have installed?
