### ISSUE TITLE
Please Update to 15.2 and add a GUI

### ISSUE THREAD

**Issue by EchocallingEarth** [GorgeousOne/TangledMazes#24]
This is an Update request with a feature request

Please update to 15.2 and add a GUI

PS if it requires premium or a donation just ask. Many server owners including myself would  I assume take full advantage of this. 

If you want to contact me or anything please feel free. Especially as I would love to have this on my servers.

**Comment by GorgeousOne** [comment]
I have a few questions concerining this update request.

The first is: What kind of bug or malfunction do you experience that make this plugin not working in 1.15? I did not test it with all it's features in the new version but I didn't expect any difficlulties with the compability.

The second question is: What features of Tangledmaze would you like to access through a GUI? If you wish for a GUI to be added it would be nice to include all functions it should fulfill.

**Comment by EchocallingEarth** [comment]
Hey, thanks for getting back to me on this. Honestly, because it had not been listed as updated we had not tested it on our 15.2 servers. With that said we will test today and update any issues etc that may arise(With the hopes that none occur and I asked an unneeded question). While testing I will discuss with the admin who inquired abut the GUI functions what he actually wanted and why.

I have some thoughts on this by want to be sure that I know what he meant first.

**Comment by EchocallingEarth** [comment]
Okay so it works great on 15.2 and for the GUI I have chosen to ignore my admin's thoughts as he clearly doesn't realize how easy this plugin is to work with and use. On that note closing this ticket. Thank you.
