### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by LokiTheGod123** [GorgeousOne/TangledMazes#28]
After running all the commands it says:started building your maze, then nothing happens
I thought i will have my maze built.

**Comment by GorgeousOne** [comment]
I am sorry to hear that the plugin isn’t working for you.
I would anyway like to ask you to provide your spigot version and steps to reproduce the bug.

**Comment by LokiTheGod123** [comment]
Ok👍

**Comment by LokiTheGod123** [comment]
Sorry for replying for so long - I didn’t have much time. I watched the tutorial today and I finally made my maze. I think the problem I had was that the size of maze I wanted to build.
It was just too big😂. Sorry for wasting your time - I could do it without opening this issue if I realized earlier that my maze was too big (it was like 250x250) 
This plugin is amazing
⭐️⭐️⭐️⭐️⭐️
