### ISSUE TITLE
1.13 materials are not recognized

### ISSUE THREAD

**Issue by SlimeDog** [GorgeousOne/TangledMazes#5]
**Describe the bug**
Attempt to build with 1.13 materials -- for example, jungle_leaves -- produce error messages in-game.

**To Reproduce**
1. Select an area
2. Mark exits
3. Run command '/tm build jungle_leaves'
4. See error in-game

**Minecraft version**
Spigot 1.13.2 latest
TangledMaze 1.2

**Comment by GorgeousOne** [comment]
The plugin is completely coded in 1.12. It will take some time to switch everything to 1.13 but it's my goal for version 1.3

**Comment by SlimeDog** [comment]
Yes, that was clear. Thus the report. :)

1.14 is just around the corner.

**Comment by GorgeousOne** [comment]
enhanced

**Comment by SlimeDog** [comment]
Spigot 1.13.2
TangledMaze 1.2.2

I'm missing something. 1.13.x materials are recognized, in the sense that one can specify them; for example
```
/tm build black_terracotta
```
but the maze is built with (white) terracotta. Or
```
/tmp/build spruce_leaves
```
but the maze is built with (oak) leaves.

TM 1.2.2 contains
```
1.12_material_lists.yml
1.13_material_lists.yml
```
but those files are not published to the _plugins/TangledMaze/_ directory. Please advise.

**Comment by GorgeousOne** [comment]
The files are not meant to show up in the directory. They are read from inside the jar. The bug is not related to it. I will look how to solve it

**Comment by SlimeDog** [comment]
Thanks. I assumed as much. Just trying to give complete information.
