### ISSUE TITLE
Exit is not recognized

### ISSUE THREAD

**Issue by SlimeDog** [GorgeousOne/TangledMazes#6]
Perhaps I misunderstand the command sequence...

**Describe the bug**
Exit is not recognized.

**To Reproduce**
1. Select an 8x8 area
2. Mark exits
3. Run command '/tm build wool'
4. Note that only one exit is produced

**Minecraft version**
Spigot 1.13.2 latest
TangledMaze 1.2
![screen shot 2019-02-06 at 8 16 48 am](https://user-images.githubusercontent.com/17748923/52355750-cc1abf80-29e7-11e9-84e3-21019f663dcc.png)
![screen shot 2019-02-06 at 8 18 06 am](https://user-images.githubusercontent.com/17748923/52355763-d0df7380-29e7-11e9-88e5-eee35f453313.png)

**Comment by GorgeousOne** [comment]
Would it be possible to also provide the cardinal direction you were looking towards in this screenshot?

**Comment by SlimeDog** [comment]
E in that screenshot. For another test, it was N.

**Comment by GorgeousOne** [comment]
yeah ok that was not the problem at all xD just a little iteration mistake.

**Comment by SlimeDog** [comment]
Please do some basic testing before throwing stuff over the wall. Making the exits is pretty fundamental to the use of the app.

**Comment by GorgeousOne** [comment]
I am going to ignore this comment. I have a long list with things to check when changing anything. Nothing is really basic to test anymore. Bugs are always happening.
I for myself find it very disrespectful of you to assume my way of working. In the end you really don't know anything about the development I'm doing.

**Comment by SlimeDog** [comment]
"Bugs are always happening" indicates that the testing process is not as complete as it should be.

Please add checking the exits to the long list. Good fortune and I wish you well.
