### ISSUE TITLE
Feature request: Make permission root unique

### ISSUE THREAD

**Issue by SlimeDog** [GorgeousOne/TangledMazes#7]
**Is your feature request related to a problem? Please describe.**
Permissions conflicts are very likely to occur with current root "tm".

**Describe the solution you'd like**
Make permissions root "tangledmaze". In general, permissions root should reflect the name of the plugin.

**Comment by GorgeousOne** [comment]
I will change that.

**Comment by SlimeDog** [comment]
Thanks.
