### ISSUE TITLE
Cannot cut or add to clipboard

### ISSUE THREAD

**Issue by SlimeDog** [GorgeousOne/TangledMazes#8]
Perhaps I misunderstand the command sequence...

**Describe the bug**
Cannot cut or add to clipboard

**To Reproduce**
1. Select an area and run **/tm start**
2. Mark exits (or not -- doesn't matter)
3. Run command **/tm cut** or **/tm add**
4. See error in-game: **Please finish your clipboard first** (in red)

**Minecraft version**
Spigot 1.13.2 latest
TangledMaze 1.2

**Comment by GorgeousOne** [comment]
Yeah never happened to me

**Comment by SlimeDog** [comment]
Closed? Is it resolved? Did I make a mistake?

**Comment by GorgeousOne** [comment]
After running /tm start you have to select another golden-blue clipboard. This one can be added/cut away from your redstone floor plan with /tm add or /tm cut

**Comment by SlimeDog** [comment]
Thank you. The instructions could be a little clearer on that point.

**Comment by GorgeousOne** [comment]
What would you suggest to write there? I mean theoretically it is not that far fetched that you need a new clip to add dor cut away somehing imo.

**Comment by SlimeDog** [comment]
Agreed. Just say so. :)    Something like:

There are three ways to edit the floor plan you created:
- adding another shape to it
- cutting away another shape
- adding or brushing away single blocks

Once you have started your floorplan, select one or more secondary shapes, then use /tm add to add the secondary shapes to your floor plan, or use /tm cut to remove the secondary shapes from your floor plan.

**Comment by GorgeousOne** [comment]
well if you think this might help other people...

**Comment by SlimeDog** [comment]
I think it would. We should never assume that everyone understands "the obvious."

**Comment by GorgeousOne** [comment]
Well it was written that it's possible to cut or add other shapes. That's not directly a step by step tutorial but probably  understandable
